services:
  - type: web
    name: validador-licencas
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn servidor_licencas_v3:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
